### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by CoutureOne** [everfu/hexo-theme-solitude#306]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Mac/Linux

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

<img width="941" alt="image" src="https://github.com/everfu/hexo-theme-solitude/assets/62696030/36eec3a6-98c1-4b2a-a2e4-981b8342e02a">
更新最新的版本运行以后出现下面报错

### 终端日志 📒

INFO  Start processing
INFO  0 (wish), 3 (do),11 (collect) book loaded in 335 ms
INFO  Hexo is running at http://localhost:4000/ . Press Ctrl+C to stop.
Unhandled rejection TypeError: /Users/couture/MyBlog/themes/solitude/layout/includes/inject/body.pug:21
    19|     if theme.mermaid
    20|         script(src=url_for(theme.cdn.mermaid_js))
  > 21|     if theme.post.share.list.includes('qrcode')
    22|         script(src=url_for(theme.cdn.qrcode))
    23| 
    24|     if theme.display_mode.universe

Cannot read properties of null (reading 'includes')
    at eval (eval at wrap (/Users/couture/MyBlog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:11982:27)
    at template (eval at wrap (/Users/couture/MyBlog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:12896:7)
    at _View._compiled (/Users/couture/MyBlog/node_modules/hexo/dist/theme/view.js:123:67)
    at _View.render (/Users/couture/MyBlog/node_modules/hexo/dist/theme/view.js:48:21)
    at /Users/couture/MyBlog/node_modules/hexo/dist/hexo/index.js:60:29
    at tryCatcher (/Users/couture/MyBlog/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/couture/MyBlog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/couture/MyBlog/node_modules/hexo/dist/hexo/router.js:43:9)
    at Readable.read (node:internal/streams/readable:737:12)
    at resume_ (node:internal/streams/readable:1255:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

^CINFO  See you again

**Comment by everfu** [comment]
已修复
