### ISSUE TITLE
[Bug]: Markdown序号生成后的问题

### ISSUE THREAD

**Issue by mc-sep** [everfu/hexo-theme-solitude#387]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

![image](https://s2.loli.net/2024/09/17/nxedtsCQc7RHqbZ.png)

![image](https://s2.loli.net/2024/09/17/Xu5sgnAGYPHd7Ec.png)

如图，当序号遇到如图片、代码块之类的东西就会断开

### 终端日志 📒

```command
INFO  Validating config
ERROR Plugin load failed: hexo-pwa
Error: Cannot find module 'lodash'
Require stack:
- J:\博客\MC-Sep\node_modules\hexo-pwa\lib\serviceWorker.js
- J:\博客\MC-Sep\node_modules\hexo-pwa\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1149:15)
    at Module._load (node:internal/modules/cjs/loader:990:27)
    at Module.require (node:internal/modules/cjs/loader:1237:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (J:\博客\MC-Sep\node_modules\hexo-pwa\lib\serviceWorker.js:11:11)
    at Module._compile (node:internal/modules/cjs/loader:1378:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Module._load (node:internal/modules/cjs/loader:1028:12)
    at Module.require (node:internal/modules/cjs/loader:1237:19)
    at req (J:\博客\MC-Sep\node_modules\hexo\dist\hexo\index.js:247:31)
    at J:\博客\MC-Sep\node_modules\hexo-pwa\index.js:14:32
    at J:\博客\MC-Sep\node_modules\hexo\dist\hexo\index.js:255:20
    at tryCatcher (J:\博客\MC-Sep\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (J:\博客\MC-Sep\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (J:\博客\MC-Sep\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (J:\博客\MC-Sep\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (J:\博客\MC-Sep\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (J:\博客\MC-Sep\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (J:\博客\MC-Sep\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (J:\博客\MC-Sep\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (J:\博客\MC-Sep\node_modules\bluebird\js\release\async.js:15:14)
INFO
  =====================[ Hexo Theme - Solitude ]=====================
       #####  ####  #     #####  ###### #     # ######   ######
      #      #    # #       #      #    #     # #      # #
       ##### #    # #       #      #    #     # #      # ######
           # #    # #       #      #    #     # #      # #
      ######  ####  ##### #####    #      ###   ######   ######
                            2.0.13
  ===================================================================
  GitHub: https://github.com/everfu/hexo-theme-solitude

INFO  Start processing
INFO  Hexo is running at http://localhost:4000/ . Press Ctrl+C to stop.
INFO  Good bye
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/everfu) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/everfu/hexo-theme-solitude/issues/387">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/387/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/387/pledge.svg">
</picture>
</a>

**Comment by mc-sep** [comment]
那个hexo pwa就是没用的

**Comment by everfu** [comment]
注意格式缩进

**Comment by mc-sep** [comment]
啊缩进？
我在markdown编辑器里都用同一行也没有这个问题啊
