### ISSUE TITLE
[Bug]: twikoo 无法加载

### ISSUE THREAD

**Issue by leaflyingl** [everfu/hexo-theme-solitude#404]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

全新安装了新版2.1.4，但是twikoo无法加载，之前在2.0.13安装twikoo没这个问题
<img width="632" alt="1728663934333" src="https://github.com/user-attachments/assets/f0947cee-9140-4aba-adfd-77f763971e6f">
twikoo 云函数运转正常
{"code":100,"message":"Twikoo 云函数运行正常，请参考 https://twikoo.js.org/frontend.html 完成前端的配置","version":"1.6.39"}

### 终端日志 📒

FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
Error: F:/hexoblog/hexoblog/source/css/_comments/comment.styl:80:33
   76|     margin 0 0 .5rem
   77|     font-size .6rem
   78|     color var(--efu-secondtext)
   79|     border-radius 8px
   80|   if hexo-config('comment.use')[1] || ',' in hexo-config('comment.use')
---------------------------------------^
   81|     &.move
   82|       if hexo-config('comment.count')
   83|         .comment-head

cannot perform 'twikoo'[(1)]
    at "#post-comment" (F:/hexoblog/hexoblog/source/css/_comments/comment.styl:55:32)

    at String.operate (F:\hexoblog\hexoblog\node_modules\stylus\lib\nodes\node.js:233:15)
    at String.operate (F:\hexoblog\hexoblog\node_modules\stylus\lib\nodes\string.js:140:22)
    at Evaluator.visitBinOp (F:\hexoblog\hexoblog\node_modules\stylus\lib\visitor\evaluator.js:575:30)
    at Evaluator.visit (F:\hexoblog\hexoblog\node_modules\stylus\lib\visitor\index.js:29:42)
    at Evaluator.visit (F:\hexoblog\hexoblog\node_modules\stylus\lib\visitor\evaluator.js:154:20)
    at Evaluator.visitBinOp (F:\hexoblog\hexoblog\node_modules\stylus\lib\visitor\evaluator.js:563:21)
    at Evaluator.visit (F:\hexoblog\hexoblog\node_modules\stylus\lib\visitor\index.js:29:42)
    at Evaluator.visit (F:\hexoblog\hexoblog\node_modules\stylus\lib\visitor\evaluator.js:154:20)
    at Evaluator.visitExpression (F:\hexoblog\hexoblog\node_modules\stylus\lib\visitor\evaluator.js:638:28)
    at Evaluator.visit (F:\hexoblog\hexoblog\node_modules\stylus\lib\visitor\index.js:29:42)
    at Evaluator.visit (F:\hexoblog\hexoblog\node_modules\stylus\lib\visitor\evaluator.js:154:20)
    at Evaluator.visitIf (F:\hexoblog\hexoblog\node_modules\stylus\lib\visitor\evaluator.js:785:19)
    at Evaluator.visit (F:\hexoblog\hexoblog\node_modules\stylus\lib\visitor\index.js:29:42)
    at Evaluator.visit (F:\hexoblog\hexoblog\node_modules\stylus\lib\visitor\evaluator.js:154:20)
    at Evaluator.visitBlock (F:\hexoblog\hexoblog\node_modules\stylus\lib\visitor\evaluator.js:716:41)
    at Evaluator.visit (F:\hexoblog\hexoblog\node_modules\stylus\lib\visitor\index.js:29:42)
    at Evaluator.visit (F:\hexoblog\hexoblog\node_modules\stylus\lib\visitor\evaluator.js:154:20)
    at Evaluator.visitGroup (F:\hexoblog\hexoblog\node_modules\stylus\lib\visitor\evaluator.js:255:24)
    at Evaluator.visit (F:\hexoblog\hexoblog\node_modules\stylus\lib\visitor\index.js:29:42)
    at Evaluator.visit (F:\hexoblog\hexoblog\node_modules\stylus\lib\visitor\evaluator.js:154:20)
    at Evaluator.visitBlock (F:\hexoblog\hexoblog\node_modules\stylus\lib\visitor\evaluator.js:716:41)
    at Evaluator.visit (F:\hexoblog\hexoblog\node_modules\stylus\lib\visitor\index.js:29:42)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/everfu) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/everfu/hexo-theme-solitude/issues/404">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/404/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/404/pledge.svg">
</picture>
</a>

**Comment by everfu** [comment]
清一下缓存试试：
```bash
hexo clean
```

**Comment by leaflyingl** [comment]
> 清一下缓存试试：
> 
> ```shell
> hexo clean
> ```

清过缓存，一样报错，不知是哪里的问题

<img width="709" alt="1728710904486" src="https://github.com/user-attachments/assets/1281dd3d-3447-43c8-8a1b-e63463b307fa">

<img width="445" alt="1728711001362" src="https://github.com/user-attachments/assets/efa8e3b8-cb7d-4dcf-bec5-38c002121314">

**Comment by leaflyingl** [comment]
<img width="625" alt="1728733258008" src="https://github.com/user-attachments/assets/22be714b-9f70-43a5-bd02-41c8d54ad9f0">

我又新申请了waline进行部署，还是报一样的错误。不管是只开一个评论还是同时开两个，都过不去。不知道是不是我的个例？究竟是哪里的问题呢？

**Comment by everfu** [comment]
稍等测试一下

**Comment by leaflyingl** [comment]
> 稍等测试一下

请问有办法没，老板？

**Comment by everfu** [comment]
未发现此问题，请更新到最新版

**Comment by everfu** [comment]
无问题

**Comment by leaflyingl** [comment]
> 无问题

那可能是个例了。请教现在的报错大概是什么原因导致的呢？已经更新到最新版了。
