### ISSUE TITLE
[Bug]: 当用文章网址采用一定长度的中文时网页二维码生成失败，QRCodejs 库报 code length overflow.

### ISSUE THREAD

**Issue by Qiu-Quanzhi** [everfu/hexo-theme-solitude#433]
### 前置确认

- [X] 我确认我运行的是最新版本的主题，并且安装了所需的依赖，在[FAQS](https://solitude-docs.efu.me/faq)中也未找到类似问题。

### ⚠️ 搜索issues中是否已存在类似问题

- [X] 我已经搜索过issues和disscussions，没有跟我遇到的问题相关的issue

### 操作系统类型?

Windows

### 运行的Hexo版本是?

Hexo 7.0.0

### 你所使用的主题版本是稳定/最新?

稳定版（main）

### 问题描述 😯

当用网址较长时网页二维码生成失败，QRCodejs 库报 code length overflow.

### 终端日志 📒

qrcode.min.js:1  Uncaught Error: code length overflow. (1684>1056)
    at b.createData (qrcode.min.js:1:5199)
    at b.makeImpl (qrcode.min.js:1:2602)
    at b.getBestMaskPattern (qrcode.min.js:1:3024)
    at b.make (qrcode.min.js:1:2028)
    at QRCode.makeCode (qrcode.min.js:1:19621)
    at new QRCode (qrcode.min.js:1:19431)
    at 一字一世界·欢迎来到我的博客！/:228:5

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/everfu) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/everfu/hexo-theme-solitude/issues/433">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/433/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/everfu/hexo-theme-solitude/issues/433/pledge.svg">
</picture>
</a>

**Comment by Qiu-Quanzhi** [comment]
原因是QRCode的默认容错率过高，调低到`L`即可。
#434 解决了该问题
